### ISSUE TITLE
New workflow architecture

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta#418]
Allow the workflow to be initialized based on a specific backup

**Comment by jesperpedersen** [comment]
@Jubilee101 

Command is

```
pgmoneta-cli -c pgmoneta.conf verify primary oldest /tmp failed
```

```
=================================================================
==583276==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 20240 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f785885970d in pgmoneta_json_create src/libpgmoneta/json.c:373:21
    #2 0x7f785894cf74 in verify_execute src/libpgmoneta/wf_verify.c:169:11
    #3 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #4 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #5 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 161920 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f78588111f0 in create_art_node src/libpgmoneta/art.c:458:33
    #2 0x7f785880d969 in art_node_insert src/libpgmoneta/art.c:670:7
    #3 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #4 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #5 0x7f785894d05e in verify_execute src/libpgmoneta/wf_verify.c:175:7
    #6 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #7 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #8 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 98670 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f7858810f8f in create_art_leaf src/libpgmoneta/art.c:434:8
    #2 0x7f785880eefa in art_node_insert src/libpgmoneta/art.c:764:10
    #3 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #4 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #5 0x7f785894d15d in verify_execute src/libpgmoneta/wf_verify.c:177:7
    #6 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #7 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #8 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 93610 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f7858810f8f in create_art_leaf src/libpgmoneta/art.c:434:8
    #2 0x7f785880d7e9 in art_node_insert src/libpgmoneta/art.c:648:7
    #3 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #4 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #5 0x7f785894cfc1 in verify_execute src/libpgmoneta/wf_verify.c:174:7
    #6 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #7 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #8 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 92345 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f7858810f8f in create_art_leaf src/libpgmoneta/art.c:434:8
    #2 0x7f785880d991 in art_node_insert src/libpgmoneta/art.c:671:7
    #3 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #4 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #5 0x7f785894d05e in verify_execute src/libpgmoneta/wf_verify.c:175:7
    #6 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #7 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #8 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 92345 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f7858810f8f in create_art_leaf src/libpgmoneta/art.c:434:8
    #2 0x7f785880eefa in art_node_insert src/libpgmoneta/art.c:764:10
    #3 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #4 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #5 0x7f785894d0f2 in verify_execute src/libpgmoneta/wf_verify.c:176:7
    #6 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #7 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #8 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 83490 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d630cf0 in realloc (build/src/pgmoneta+0xa1cf0) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f78588e0501 in pgmoneta_append src/libpgmoneta/utils.c:1165:15
    #2 0x7f78588f5cfa in pgmoneta_value_create src/libpgmoneta/value.c:141:33
    #3 0x7f7858810ff1 in create_art_leaf src/libpgmoneta/art.c:442:7
    #4 0x7f785880d7e9 in art_node_insert src/libpgmoneta/art.c:648:7
    #5 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #6 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #7 0x7f785894cfc1 in verify_execute src/libpgmoneta/wf_verify.c:174:7
    #8 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #9 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #10 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 82225 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d630cf0 in realloc (build/src/pgmoneta+0xa1cf0) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f78588e0501 in pgmoneta_append src/libpgmoneta/utils.c:1165:15
    #2 0x7f78588f5cfa in pgmoneta_value_create src/libpgmoneta/value.c:141:33
    #3 0x7f7858810ff1 in create_art_leaf src/libpgmoneta/art.c:442:7
    #4 0x7f785880eefa in art_node_insert src/libpgmoneta/art.c:764:10
    #5 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #6 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #7 0x7f785894d0f2 in verify_execute src/libpgmoneta/wf_verify.c:176:7
    #8 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #9 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #10 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 40480 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f78588f57bf in pgmoneta_value_create src/libpgmoneta/value.c:69:26
    #2 0x7f7858810ff1 in create_art_leaf src/libpgmoneta/art.c:442:7
    #3 0x7f785880eefa in art_node_insert src/libpgmoneta/art.c:764:10
    #4 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #5 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #6 0x7f785894d15d in verify_execute src/libpgmoneta/wf_verify.c:177:7
    #7 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #8 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #9 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 40480 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f78588f57bf in pgmoneta_value_create src/libpgmoneta/value.c:69:26
    #2 0x7f7858810ff1 in create_art_leaf src/libpgmoneta/art.c:442:7
    #3 0x7f785880eefa in art_node_insert src/libpgmoneta/art.c:764:10
    #4 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #5 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #6 0x7f785894d0f2 in verify_execute src/libpgmoneta/wf_verify.c:176:7
    #7 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #8 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #9 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 40480 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f78588f57bf in pgmoneta_value_create src/libpgmoneta/value.c:69:26
    #2 0x7f7858810ff1 in create_art_leaf src/libpgmoneta/art.c:442:7
    #3 0x7f785880d991 in art_node_insert src/libpgmoneta/art.c:671:7
    #4 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #5 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #6 0x7f785894d05e in verify_execute src/libpgmoneta/wf_verify.c:175:7
    #7 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #8 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #9 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 40480 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f78588f57bf in pgmoneta_value_create src/libpgmoneta/value.c:69:26
    #2 0x7f7858810ff1 in create_art_leaf src/libpgmoneta/art.c:442:7
    #3 0x7f785880d7e9 in art_node_insert src/libpgmoneta/art.c:648:7
    #4 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #5 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #6 0x7f785894cfc1 in verify_execute src/libpgmoneta/wf_verify.c:174:7
    #7 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #8 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #9 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 20240 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d6308d3 in malloc (build/src/pgmoneta+0xa18d3) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f785880c725 in pgmoneta_art_create src/libpgmoneta/art.c:312:8
    #2 0x7f78588595d6 in pgmoneta_json_put src/libpgmoneta/json.c:359:7
    #3 0x7f785894cfc1 in verify_execute src/libpgmoneta/wf_verify.c:174:7
    #4 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #5 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #6 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

Indirect leak of 17677 byte(s) in 1265 object(s) allocated from:
    #0 0x55c52d630cf0 in realloc (build/src/pgmoneta+0xa1cf0) (BuildId: 56ffd3912928b18e0349960d11bd98ab442a820c)
    #1 0x7f78588e0501 in pgmoneta_append src/libpgmoneta/utils.c:1165:15
    #2 0x7f78588f5cfa in pgmoneta_value_create src/libpgmoneta/value.c:141:33
    #3 0x7f7858810ff1 in create_art_leaf src/libpgmoneta/art.c:442:7
    #4 0x7f785880d991 in art_node_insert src/libpgmoneta/art.c:671:7
    #5 0x7f785880d50f in pgmoneta_art_insert src/libpgmoneta/art.c:355:14
    #6 0x7f78588596ce in pgmoneta_json_put src/libpgmoneta/json.c:365:11
    #7 0x7f785894d05e in verify_execute src/libpgmoneta/wf_verify.c:175:7
    #8 0x7f78588f8cfe in pgmoneta_verify src/libpgmoneta/verify.c:123:11
    #9 0x55c52d67f0d5 in accept_mgt_cb src/main.c:1049:13
    #10 0x7f785933a5d2 in ev_invoke_pending /home/jews/PostgreSQL/pgagroal/libev/ev.c:3770:11

SUMMARY: AddressSanitizer: 924682 byte(s) leaked in 17710 allocation(s).
```
